### ISSUE TITLE
Execution interrupted or reached maximum runtime

### ISSUE THREAD

**Issue by fal3n-4ngel** [edaplayground/eda-playground#82]
I am writing this issue from my college lab, where I am forced to use this site in order to realize logic gates for my so called Digital Lab.
It works as long as no more than 1 person uses it,but if any more than 2 people uses it
```Execution interrupted or reached maximum runtime.```
This error keeps popping up.
Hope u guys fix it before my semester ends..

**Comment by mpataylor** [comment]
Hi Adithya,

I'm sorry you are having problems with EDA Playground. This seems to be happening at busy times, at the moment. Busy time is basically the working day in India. If you are experiencing this, please try a quieter time.

Matthew

From: Adithya Krishnan ***@***.***>
Sent: Thursday, June 8, 2023 6:11 AM
To: edaplayground/eda-playground ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [edaplayground/eda-playground] Potato Server!! (Issue #82)


I am writing this issue from my college lab, where I am forced to use this site in order to realize logic gates for my so called Digital Lab.
It works as long as no more than 1 person uses it
Execution interrupted or reached maximum runtime.
This error keeps popping up.
Hope u guys fix it before my semester ends..

-
